# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bash' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bash
pod 'Firebase'
pod 'FirebaseCore', '~> 6.4'
pod 'FirebaseDatabase', '~> 6.1'
pod 'Firebase/Analytics'
pod 'FirebaseUI'
pod 'FacebookCore'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'PromiseKit'
pod 'PromiseKit/Alamofire'
pod 'ReachabilitySwift'

end
